openapi: 3.0.0
info:
  title: common cms service
  version: 1.0.0
tags:
  - name: site
    description: Operations related to sites
  - name: page
    description: Operations related to pages
paths:
  /sites:
    get:
      summary: Get Sites
      operationId: getSites
      tags:
        - site
      responses:
        '200':
          description: Successful response
    post:
      summary: Create Site
      operationId: postSite
      tags:
        - site
      responses:
        '201':
          description: Site created successfully
    put:
      summary: Update Site
      operationId: putSite
      tags:
        - site
      responses:
        '200':
          description: Successful response
    delete:
      summary: Delete Site
      operationId: deleteSite
      tags:
        - site
      responses:
        '204':
          description: Site deleted successfully
  /sites/{siteId}/pages:
    get:
      summary: Get Pages for a Site
      operationId: getPages
      tags:
        - page
      parameters:
        - name: siteId
          in: path
          required: true
          description: ID of the site
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
    post:
      summary: Create Page for a Site
      operationId: postPage
      tags:
        - page
      parameters:
        - name: siteId
          in: path
          required: true
          description: ID of the site
          schema:
            type: integer
      responses:
        '201':
          description: Page created successfully
    put:
      summary: Update Page for a Site
      operationId: putPage
      tags:
        - page
      parameters:
        - name: siteId
          in: path
          required: true
          description: ID of the site
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
    delete:
      summary: Delete Page for a Site
      operationId: deletePage
      tags:
        - page
      parameters:
        - name: siteId
          in: path
          required: true
          description: ID of the site
          schema:
            type: integer
      responses:
        '204':
          description: Page deleted successfully
